version: "3.7"
services:
  lb:
    image: nginx:latest
    container_name: lb
    ports:
    - 80:80
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      projector:
        ipv4_address: 10.0.0.10

  node1:
    image: nginx:latest
    container_name: node1
    volumes:
    - "./node1.html:/usr/share/nginx/html/index.html"
    networks:
      projector:
        ipv4_address: 10.0.0.11

  node2:
    image: nginx:latest
    container_name: node2
    volumes:
    - "./node2.html:/usr/share/nginx/html/index.html"
    networks:
      projector:
        ipv4_address: 10.0.0.12

  node3:
    image: nginx:latest
    container_name: node3
    volumes:
    - "./node3.html:/usr/share/nginx/html/index.html"
    networks:
      projector:
        ipv4_address: 10.0.0.13

networks:
  projector:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
          #gateway: 10.0.0.1
